# Generated by Django 5.1.4 on 2024-12-10 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('RNB', 'R&B'), ('COUNTRY', 'Country'), ('ELECTRONIC', 'Electronic'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='songoftheday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
