# Generated by Django 5.1.4 on 2024-12-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_songoftheday_likes_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='songoftheday',
            name='post_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
